language: node_js
node_js:
  - "node"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
jobs:
  include:
    - stage: build
      script: yarn build
    - stage: lint
      script: yarn lint:ci
