name: release

on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 50
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        git config user.email "andrewusher00@gmail.com"
        git config user.name "Andrew Usher"
        yarn
        yarn release
        git push --follow-tags origin develop
